name: Publish production update

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Update message"
        required: false

jobs:
  publish_update:
    name: Publish update
    type: update
    defaults:
      run:
        working_directory: ./apps/beacon
    params:
      channel: production
      message: ${{ inputs.message || 'Manual update' }}
