name: Publish production update

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Update message"
        required: false

jobs:
  publish_update:
    name: Publish update
    defaults:
      run:
        working_directory: ./apps/beacon
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Publish update
        run: npx eas-cli update --channel production --non-interactive --message "${{ inputs.message || 'Manual update' }}"
